### ISSUE TITLE
Add exact phrase searching

### ISSUE THREAD

**Issue by Stiofan** [AyeCode/geodirectory#595] opened 2019-01-29 14:21 UTC
adding the searched text in "quotes" should search for the exact phrase, this should also search exact tags like "hotel rooms"
https://wpgeodirectory.com/support/topic/search-not-working-correctlry/

**Comment by Stiofan** [comment] 2019-03-07 15:42
@kprajapatii lets also make it that if "quotes" are used that the search is limited to exact text in the title or description only.  Let me know if u have any questions.

**Comment by alexrollin** [comment] 2019-03-20 16:59
Is this going to cover this case here:
https://wpgeodirectory.com/support/topic/search-not-working-anymore/page/2/#post-475560

Or do we need another issue for that one? The issue is tag results are not returning. Whether it is multiword or multilingual rtd.

**Comment by kprajapatii** [comment] 2019-03-22 13:32
Fixed via https://github.com/AyeCode/geodirectory/pull/664/commits/6989073ca76e37cb4f59f349d6ed067e744e4417

@alexrollin

**Comment by alexrollin** [comment] 2019-03-22 14:10
can someone look at this one please?

https://wpgeodirectory.com/support/topic/search-not-working-anymore/page/2/#post-475560

**Closed** 2019-03-22 15:23 UTC
Labels: For: Developer, Priority: Medium, enhancement

**Comment by Stiofan** [comment] 2019-03-22 16:14
@alexrollin i have made some changes here that should resolve this for the user
