### ISSUE TITLE
phantom yellow line

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#540] opened 2018-12-17 11:29 UTC
if listings page is resized a phantom yellow line can appear to the left of review stars

https://www.revue.pw/prod/

![image](https://user-images.githubusercontent.com/114659/50084464-5ff5b980-01f7-11e9-8850-ad9f4f7c6634.png)

![image](https://user-images.githubusercontent.com/114659/50374486-6b7a2380-05ef-11e9-8720-08a517e5449e.png)

reporting topic
https://wpgeodirectory.com/support/topic/rating-style-issues/page/2/#post-459323

**Comment by Stiofan** [comment] 2019-03-11 14:02
Can't view link. this is usually caused by browser zoom, closing for now, will reopen if thats not the case.

**Closed by Stiofan** 2019-03-11 14:02 UTC
Labels: Can't Replicate
