### ISSUE TITLE
Select field default option not updating from settings

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#243] opened 2018-04-06 16:07 UTC
Steps to recreate

create a place select field
set one of the values as default
open add listing page with admin user
verify the field is working and default is present and set.
change default to another selection
refresh add listing page, see default does not change
create a new user
open incognito, login with new user, view add listing page
verify that default value is not updated

related topic
https://wpgeodirectory.com/support/topic/select-field/

**Comment by Stiofan** [comment] 2018-04-13 13:14
related to #200 this is not a bug but rather a misunderstanding of the settings, i plan to work on this, so closing this as a duplicate.

**Closed by Stiofan** 2018-04-13 13:14 UTC
Labels: duplicate
