### ISSUE TITLE
option to upload image from media library 

### ISSUE THREAD

**Issue by 1naveengiri** [AyeCode/geodirectory#1775] opened 2021-06-21 18:42 UTC
https://secure.helpscout.net/conversation/1548847616/21003?folderId=3803506

**Comment by 1naveengiri** [comment] 2023-06-01 10:38
https://secure.helpscout.net/conversation/2253764320/43863/

**Comment by kprajapatii** [comment] 2023-06-01 10:58
Duplicate of https://github.com/AyeCode/geodirectory/issues/2355

**Closed by kprajapatii** 2023-06-01 10:58 UTC
Labels: enhancement, For: Developer
