### ISSUE TITLE
Feature request: a widget to display tags

### ISSUE THREAD

**Issue by nicolaslimet** [AyeCode/geodirectory#2655] opened 2024-08-15 09:27 UTC
Client request a widget/block to display tags, in the same way as does GD > Categories

https://secure.helpscout.net/conversation/2680135829/59311?folderId=3803511

**Comment by kprajapatii** [comment] 2024-12-26 13:26
Duplicate of #2634

**Closed by kprajapatii** 2024-12-26 13:26 UTC
Labels: enhancement, For: Developer
