### ISSUE TITLE
Add listing upload image field related issue in Safari browser

### ISSUE THREAD

**Issue by 1naveengiri** [AyeCode/geodirectory#2217] opened 2022-09-29 11:05 UTC
https://secure.helpscout.net/conversation/2020117295/36080/
https://secure.helpscout.net/conversation/2020072858/36077?folderId=3812058

possible fix: 
```
 body.geodir-page-add .bsui input {
    position: initial !important;
}
```

**Comment by kprajapatii** [comment] 2022-10-07 13:52
Not able to reproduce, just assign me if you see new customer with similar issue.

@1naveengiri

**Comment by 1naveengiri** [comment] 2023-08-03 14:34
https://secure.helpscout.net/conversation/2320638439/46032?folderId=3812058
https://secure.helpscout.net/conversation/2315121094/45832?folderId=3812058

**Comment by 1naveengiri** [comment] 2023-10-31 10:27
https://secure.helpscout.net/conversation/2404545747/48568?folderId=3812058

**Comment by Stiofan** [comment] 2023-11-03 13:48
Hopefully this is fixed in latest AUI, if not please reopen.

**Comment by 1naveengiri** [comment] 2023-11-08 14:40
@Stiofan  I can still reproduce it even after the latest plugin update.
https://secure.helpscout.net/conversation/2404545747/48568/

**Comment by Stiofan** [comment] 2023-11-09 09:10
@1naveengiri i can't replicate.  Please let me know if anyone else reports this.

**Comment by Stiofan** [comment] 2023-11-14 13:20
was able to replicate once i updated safari, the fix was only applying to BS style and not legacy, I have added a fix in AUI.

**Closed by Stiofan** 2023-11-14 13:20 UTC
Labels: bug, For: Developer

**Comment by 1naveengiri** [comment] 2024-12-05 08:13
`
body.geodir-page-add input[type="file"] {
   position: initial !important;
}`

https://secure.helpscout.net/conversation/2757515598/62506
